version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "microlam-demo"
s3_bucket = "microlam-deploy"
s3_prefix = "microlam-demo"
region = "eu-west-1"
profile = "microlam"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
